[package]
name = "rustymind"
version = "0.1.0"
authors = ["ondras"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
rand = "0.7.3"